project:
  type: website
  output-dir: _site

website:
  title: "PCTNI: Propensity to Cycle Tool for Northern Ireland"
  navbar:
    left:
      - href: index.qmd
        text: Home

resources:
  - "*.pmtiles"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full
