name: Deploy Quarto Website

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write # Allow writing to the gh-pages branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Download release from private repo
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          # list the releases in the pctni/ui repository
          gh release list --repo pctni/ui
          # Check if the release exists
          if ! gh release list --repo pctni/ui | grep -q "pmtiles-data-v1.0"; then
            echo "❌ Release pmtiles-data-v1.0 not found in pctni/ui repository"
            exit 1
          fi
          # Download the release with explicit repo specification
          gh release download pmtiles-data-v1.0 --repo pctni/ui
          # Verify all required pmtiles files are present
          echo "📋 Verifying PMTiles files..."
          required_files=("route_network_fastest.pmtiles" "route_network_quietest.pmtiles" "corenet_network_ni.pmtiles" "cycle_net_processed.pmtiles" "gap_map.pmtiles" "Local_Authority.pmtiles")
          for file in "${required_files[@]}"; do
            if [ ! -f "$file" ]; then
              echo "❌ Missing required file: $file"
              exit 1
            else
              echo "✅ Found: $file ($(du -h "$file" | cut -f1))"
            fi
          done
          echo "🎉 All PMTiles files verified successfully"

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html # If set, it will be equivalent to `quarto render --to html`
          path: ./index.qmd # Path to the Quarto file to render

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          # Use the PAT stored as a secret
          personal_token: ${{ secrets.GH_PAT }} 
          # Target repository
          external_repository: pctni/pctni.github.io
          # Branch to deploy to in the target repository
          publish_branch: gh-pages
          # Directory containing the rendered site (adjust if needed)
          publish_dir: ./_site
          # User deploying the pages
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          # Commit message
          commit_message: Deploy Quarto dashboard from ui repository ${{ github.sha }}
          # Allow publishing empty commits if needed (e.g., first deploy)
          allow_empty_commit: true
          # Keep history or force push
          force_orphan: true # Creates a clean history on gh-pages
