name: Deploy Quarto Website

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write # Allow writing to the gh-pages branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      # Render and Publish directly to the target repository's gh-pages branch
      - name: Publish to pctni.github.io
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages # Publish to the gh-pages branch
          # Use a Personal Access Token (PAT) with repo scope stored as a secret
          # This PAT needs access to the pctni/pctni.github.io repository
          # Create a secret named GH_PAT in the ui repository settings
          github-token: ${{ secrets.GH_PAT }}
          # Specify the target repository
          target-repo: pctni/pctni.github.io
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }} # Pass the PAT to the environment as well
